In [1]:
import numpy as np

np.random.randint(150,191,size=10)

array([160, 181, 154, 153, 190, 165, 174, 152, 170, 182])

In [4]:
rnd = np.random.randn(5) * 10 + 165
rnd

array([151.04679467, 158.08025584, 153.22867796, 144.24883929,
       175.20471971])

In [5]:
rnd.round(2)

array([151.05, 158.08, 153.23, 144.25, 175.2 ])

In [7]:
rnd.astype(int)

array([151, 158, 153, 144, 175])

In [8]:
nums = np.random.normal(loc=165, scale=10, size=(3,4)).round(2)
nums

array([[163.71, 168.54, 169.29, 166.17],
       [177.48, 156.97, 157.  , 154.52],
       [158.92, 164.99, 168.7 , 168.64]])

In [9]:
a = np.arange(10)
np.random.shuffle(a)
a

array([8, 7, 1, 4, 6, 3, 5, 9, 2, 0])

In [10]:
np.random.permutation([2,4,6,8,10])

array([ 6,  8, 10,  2,  4])

In [12]:
a = np.arange(1,51)
b = np.random.shuffle(a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [20]:
def train_test_split(array, data_ratio=0.8):
  flat_array = array.flatten()
  np.random.shuffle(flat_array)

  split_idx = int(len(flat_array) * data_ratio)

  train_data = flat_array[:split_idx]
  test_data = flat_array[split_idx:]

  return train_data,test_data

array = np.arange(1,51).reshape(5,10)
train_data, test_data = train_test_split(array)
print("train: ",train_data)
print("test: ",test_data)

train:  [36 12 37  9 23 41 50 38 13 20 21 25  1 24 18 34 29 15 22 31 10 45 40 19
 39 44 26 43  5 48 49 47 35  3 32 42 33 11 28  4]
test:  [ 7 16  8 14  2 30 17 46 27  6]


In [21]:
arr_2d =np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9],
                  [0,1,2]])
arr_2d[1: , 0:2]

array([[4, 5],
       [7, 8],
       [0, 1]])

In [23]:
np_array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
np_array % 2 == 0

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [24]:
np_array[ np_array % 2 == 0 ]

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [25]:
import numpy as np
import time

arr_a = np.random.rand(100)
arr_b = np.random.rand(100)
result = np.zeros(100)

In [26]:
start = time.time()
for i in range(len(arr_a)):
  result[i] = arr_a[i] * arr_b[i]
end = time.time()
print("소요시간: ", end - start)

소요시간:  0.0005335807800292969


In [27]:
start = time.time()
result = arr_a * arr_b
end =time.time()
print("소요시간: ", end - start)

소요시간:  0.0002627372741699219


In [28]:
arr = np.array([[1,2,3,4,5],
                [1,2,3,4,5],
                [1,2,3,4,5],
                [1,2,3,4,5],
                [1,2,3,4,5],
                ])
print(np.sum(arr, axis = 0))
print(np.sum(arr, axis = 1))
np.sum(arr, axis=(0,1))

[ 5 10 15 20 25]
[15 15 15 15 15]


75

In [29]:
n = 1000
arr = np.random.rand(n,n)

In [30]:
sum_naive = 0
start = time.time()
for i in range(n):
  for j in range(n):
    sum_naive += arr[i,j]
end = time.time()
print(n, 'x', n, "배열의 원소 합", sum_naive, "\n계산 시간: ", end-start)

1000 x 1000 배열의 원소 합 500294.1492639159 
계산 시간:  0.4703636169433594


In [31]:
start = time.time()
sum_reduction = np.sum(arr, axis = (0,1))
end = time.time()
print(n, 'x', n, "배열의 원소 합", sum_naive, "\n계산 시간: ", end-start)

1000 x 1000 배열의 원소 합 500294.1492639159 
계산 시간:  0.0018854141235351562


In [32]:
a = np.array([[1,2],[1,-3]])
b = np.array([6,1])
s = np.linalg.solve(a,b)
print(s)

[4. 1.]


In [33]:
a = np.array([[2,1],[4,5]])
det_a = np.linalg.det(a)
b = np.array([[1,2],[3,-6]])
det_b = np.linalg.det(b)
print(det_a,det_b)

6.0 -12.0


In [34]:
a = np.array([[1,2,-1],[2,-1,3],[1,2,1]])
b = np.array([0,9,8])
s = np.linalg.solve(a,b)
print(s)

[-0.4  2.2  4. ]


In [35]:
A = np.array([[1,1,-1],[2,-1,3],[1,2,1]], dtype = 'int32')
det_A = np.linalg.det(A)
print(det_A)

-11.000000000000002


In [44]:
a = np.arange(10,18).reshape(2,4)
b = np.arange(12).reshape(3,4)
c = np.arange(8).reshape(2,4)
d = list(range(4))
print(a, end = "\n\n")
print(b, end = "\n\n")
print(c, end = "\n\n")
print(d)

[[10 11 12 13]
 [14 15 16 17]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[0 1 2 3]
 [4 5 6 7]]

[0, 1, 2, 3]


In [45]:
np.concatenate((a,b))

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
np.vstack((a,b))

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
np.vstack((a,d))

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [ 0,  1,  2,  3]])

In [49]:
np.vstack((a,b,d))

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3]])

In [50]:
np.hstack((a,c))

array([[10, 11, 12, 13,  0,  1,  2,  3],
       [14, 15, 16, 17,  4,  5,  6,  7]])

In [51]:
np.hstack((a,b))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3

In [52]:
np.r_[a,b]

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
a = np.array([1,2,3])
b = np.array([10,20,30])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[10,20,30],[40,50,60]])

In [55]:
np.r_[a,b]

array([ 1,  2,  3, 10, 20, 30])

In [56]:
np.r_[a,4,5,6,b]

array([ 1,  2,  3,  4,  5,  6, 10, 20, 30])

In [57]:
np.r_[[0]*3,5,6]

array([0, 0, 0, 5, 6])

In [58]:
np.r_[c,d]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30],
       [40, 50, 60]])

In [60]:
np.r_[a.reshape(-1,1), b.reshape(-1,1)]

array([[ 1],
       [ 2],
       [ 3],
       [10],
       [20],
       [30]])

In [61]:
np.concatenate((a.reshape(-1,1), b.reshape(-1,1)), axis = 1)

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [62]:
np.c_[a,b]

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [64]:
np.column_stack([a,b])

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [65]:
np.concatenate((c.T,d.T), axis=1)

array([[ 1,  4, 10, 40],
       [ 2,  5, 20, 50],
       [ 3,  6, 30, 60]])

In [83]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [85]:
a = np.logspace(0,5,6).round(10)
a

array([1.e+00, 1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05])

In [86]:
np.log10(a)

array([0., 1., 2., 3., 4., 5.])

In [87]:
a = np.array([1,3,4])
np.insert(a,1,2)

array([1, 2, 3, 4])

In [88]:
b = np.array([[1,1], [2,2], [3,3]])
np.insert(b,1,4, axis=0)

array([[1, 1],
       [4, 4],
       [2, 2],
       [3, 3]])

In [89]:
np.insert(b,1,4, axis = 1)

array([[1, 4, 1],
       [2, 4, 2],
       [3, 4, 3]])

In [90]:
c = np.array([[1,2,3],[4,5,6]])
np.flip(c, axis=1)

array([[3, 2, 1],
       [6, 5, 4]])

In [91]:
np.flip(c, axis=0)

array([[4, 5, 6],
       [1, 2, 3]])

In [93]:
b = np.array([[1,1],[2,2],[3,3]])
np.insert(b,1,[1,2,3], axis=1)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

1) numpy의 arange() 함수를 사용하여 1에서 45까지의 연속적인 번호 생성.

In [131]:
a =np.arange(1,46)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

2) 랜덤 씨드값 85로 설정, 그런 다음 이 배열을 랜덤하게 섞어서(shuffle) 첫 6개 숫자를 슬라이싱, 그 결과를 lotto라는 변수에 할당 후 출력

In [132]:
np.random.seed(85)
np.random.shuffle(a)
lotto = a[:6]
lotto

array([22,  9, 15, 44, 39, 37])

3) lotto 배열을 정렬 후 출력, 추가번호 출력, 추가번호는 7번째 숫자 출력.

In [101]:
sort_lot = np.sort(lotto)
print(sort_lot, end=" ")
print("추가번호= ", a[8])

[ 9 15 22 37 39 44] 추가번호=  21


4) 다음과 같이 0에서 24까지의 값을 가지는 5 x 5 크기의 2차원 행렬 n_arr 출력

In [116]:
n_arr = np.arange(25)
n_arr = n_arr.reshape(5,5)
n_arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

5) 첫 원소, 마지막 원소 출력 (마지막 원소 출력할떈 반드시 음수 사용)

In [105]:
print("첫 원소: ",n_arr[0])
print("마지막 원소: ",n_arr[-1])

첫 원소:  0
마지막 원소:  24


6) 슬라이싱 적용하여 출력

In [117]:
n_arr[:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

7) 슬라이싱 적용하여 출력

In [119]:
n_arr[:,[0,2,4]]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19],
       [20, 22, 24]])

8) reshape() 사용하여 출력

In [121]:
n_arr[:2].reshape(-1,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

난수로된 2 x 2 x 2 배열 생성

In [126]:
a = np.random.rand(2,2,2)
a

array([[[0.47642166, 0.4167415 ],
        [0.9599303 , 0.66566491]],

       [[0.65571357, 0.69839402],
        [0.23767492, 0.12118492]]])

9) 최대값

In [129]:
print("a 배열의 최대값: ",a.max())

a 배열의 최대값:  0.9599302963885098


10) 최소값

In [130]:
print("a 배열의 최소값: ",a.min())

a 배열의 최소값:  0.12118491980232848
